# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12e1c2a5dd9d41816478a438999da741040ffa5be77431bfbac017e46139240106dcf0ff661c50dcd04a9781343cd199091da541b8362ca2267c837642524ead

test:
  secret_key_base: 2f19c628dc38e9e30c0d2ba9f0ed8bb8468e937caddf36e1959b39bd46bfb105b0666a6f9ade06bae7bea81c1f5c6f9dc254008db579210809d707d611481e81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
